on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Windows]
    steps:
    - name: Setup Python 3.9 Environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
     env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: ./ # set this to the path to your web app project, defaults to the repository root

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
