on:
  push:
    branches: main
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./
  AZURE_FUNCTIONAPP_NAME : fapp-kvelo-eus2-int-devops-01
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - name: Setup Python 3.7 Environments
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Check out repository
      with:
        repository: TeamKagoolLtd/azurefunctonapps-github
       # ref: v1.0
      uses: actions/checkout@v2
   
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: Login via Az module
      uses: azure/login@v1
      with:
          creds: ${{ secrets.KAGOOL_GITHUB_CREDENTIALS }}
          enable-AzPSSession: true
          
    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
